# Category-level selection

[categories]
git-configuration="true"
vscode-settings="false"
macos-finder="true"
macos-dock="true"
macos-keyboard="false"
macos-trackpad="false"
macos-screenshots="true"

# Item-level selection

[homebrew-packages]
git
jq

[homebrew-casks]
firefox
vlc

[app-store]
123456789

[vscode-extensions]
publisher.extension-a
publisher.extension-b

[workspace-folders]
Projects
Development

[git-repositories]
project-a
project-b
