# ==========================================
# Разработка
# ==========================================

visual-studio-code
iterm2
termius

# ==========================================
# Интерфейс
# ==========================================

jordanbaird-ice

# ==========================================
# VPN
# ==========================================

karing

# ==========================================
# Утилиты
# ==========================================

appcleaner
keka

# ==========================================
# Удаленный доступ
# ==========================================

rustdesk

# ==========================================
# Медиа
# ==========================================

iina
vlc
plex
telegram