# ==========================================
# Remote Development
# ==========================================

ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode.remote-explorer

# ==========================================
# Git
# ==========================================

eamodio.gitlens
github.vscode-pull-request-github

# ==========================================
# Containers
# ==========================================

ms-azuretools.vscode-docker

# ==========================================
# Languages
# ==========================================

redhat.vscode-yaml

# ==========================================
# Markdown
# ==========================================

yzhang.markdown-all-in-one

# ==========================================
# Editor
# ==========================================

editorconfig.editorconfig

# ==========================================
# Localization
# ==========================================

ms-ceintl.vscode-language-pack-ru

# ==========================================
# Themes & Icons
# ==========================================

github.github-vscode-theme
pkief.material-icon-theme

# ==========================================
# Code Quality
# ==========================================

usernamehw.errorlens
streetsidesoftware.code-spell-checker